import type { ActorRole, SkillStatus } from "./domain";

export const PRODUCT_NAME = "Skills Repo";

export const STATUS_LABELS: Record<SkillStatus, string> = {
  draft: "草稿",
  pending_review: "待审核",
  published: "已发布",
  deprecated: "已下架",
  archived: "已归档",
};

export const ROLE_LABELS: Record<ActorRole, string> = {
  employee: "员工",
  admin: "管理员",
};

export const UI_COPY = {
  loading: `正在加载 ${PRODUCT_NAME}...`,
  header: {
    eyebrow: "内部仓库",
    role: "角色",
    resultCount: "当前结果",
    description:
      "面向团队复用的内部 Skills 控制台，支持发现、审核、版本追踪和受控发布。",
    tags: {
      collectedSkills: "已收录 Skills",
      controlledSources: "受控 Git 来源",
      versionAudit: "版本与审计记录",
    },
  },
  workspaces: {
    repository: "Skills 仓库",
    mine: "我的发布",
    review: "审核队列",
  },
  actions: {
    logout: "登出",
    newSkill: "新建 Skill",
    importGit: "导入 Git",
    publish: "发布",
    approve: "通过",
    reject: "驳回",
    submitReview: "提交审核",
    deprecate: "下架",
    archive: "归档",
    apply: "应用",
    edit: "编辑",
    close: "关闭",
    saveDraftVersion: "保存草稿版本",
    createDraft: "创建草稿",
    upgradeTrackedVersion: "升级追踪版本",
    trackCurrentVersion: "追踪当前版本",
  },
  install: {
    title: "安装",
    description: "下载和命令会安装当前发布版本；版本追踪只记录你正在使用的版本。",
    trackingTitle: "版本追踪",
    trackingHelp: "记录你使用的版本，不会下载安装到本机。",
    targetTool: "目标工具",
    downloadPackage: "下载 Skill 包",
    copyCommand: "复制安装命令",
    copying: "正在复制",
    copied: "安装命令已复制",
    copyFailed: "复制失败，请手动复制命令",
    viewInstructions: "查看安装说明",
    hideInstructions: "收起安装说明",
    instructionsTitle: "安装说明",
    commandFor: "命令",
    steps: [
      "下载当前版本的 .zip 包。",
      "将压缩包解压到目标工具的 skills 目录。",
      "确认解压后的目录中包含 SKILL.md。",
    ],
    unavailableReasons: {
      not_published: "只有已发布 Skill 可以下载安装。",
      no_current_version: "暂无当前发布版本，无法生成安装包。",
    },
  },
  stats: {
    totalSkills: "Skills 总数",
    published: "已发布",
    pendingReview: "待审核",
    categories: "分类数",
    recentlyUpdated: "最近更新",
  },
  filters: {
    search: "搜索",
    category: "分类",
    status: "状态",
    teamOrSource: "团队/来源",
    tool: "工具",
    versionState: "版本状态",
    searchPlaceholder: "搜索 Skills、标签、团队...",
    allCategories: "全部分类",
    allStatuses: "全部状态",
    allTeamsOrSources: "全部团队/来源",
    allTools: "全部工具",
    allVersionStates: "全部版本状态",
    upgradeAvailable: "有可升级版本",
    current: "已是最新",
    notTracked: "未追踪",
    viewMode: "视图模式",
    gridView: "网格视图",
    tableView: "表格视图",
  },
  pagination: {
    range: "{start}-{end} / {total}",
    first: "首页",
    previous: "上一页",
    next: "下一页",
    last: "末页",
    page: "第 {page} 页",
  },
  admin: {
    console: "后台操作",
    employeeConsole: "个人发布操作",
    reviewConsole: "审核操作",
    selected: "已选",
    category: "分类",
  },
  list: {
    title: "Skills 列表",
    updatedAt: "更新时间",
    currentVersion: "当前版本",
    source: "来源",
    versions: "版本",
    maintainers: "维护人",
  },
  detail: {
    eyebrow: "Skill 详情",
    noRelease: "暂无线上版本",
    upgradeTitle: "有可升级版本",
    upgradeText: "你当前追踪 {trackedVersion}，线上版本是 {currentVersion}。",
    basicInformation: "基础信息",
    category: "分类",
    tools: "适用工具",
    maintainingTeam: "维护团队",
    maintainers: "维护人",
    owner: "创建者",
    visibility: "可见范围",
    installMethod: "安装方式",
    dependencies: "依赖说明",
    none: "无",
    readme: "README / 使用说明",
    versionHistory: "版本历史",
    recentAuditTrail: "最近审计记录",
    reviewState: "审核状态",
    rejectionReason: "驳回原因",
    noMatches: "当前筛选条件下没有匹配的 Skill。",
    published: "发布于",
    draft: "草稿",
    by: "由",
  },
  visibility: {
    personal: "个人发布区",
    public: "公共仓库",
  },
  review: {
    rejectionPrompt: "请输入驳回原因",
  },
  editor: {
    controlledGit: "受控 Git",
    skillEditor: "Skill 编辑",
    importTitle: "从受控 Git 导入",
    editTitle: "编辑 Skill",
    createTitle: "新建 Skill",
    repositoryUrl: "仓库 URL",
    repositoryName: "仓库名称",
    skillName: "Skill 名称",
    category: "分类",
    description: "描述",
    compatibleTools: "适用工具",
    maintainingTeam: "维护团队",
    tags: "标签",
    maintainers: "维护人",
    version: "版本号",
    dependencies: "依赖",
    installMethod: "安装方式",
    changelog: "更新说明",
    markdown: "Markdown 内容",
    skillMarkdown: "SKILL.md 内容",
    referencesTitle: "references/ 引用文件",
    scriptsTitle: "scripts/ 脚本文件",
    assetGroupHelp: "可选文本文件；保存后会随当前版本进入下载包。",
    assetGroupEmpty: "未添加文件时，此目录不会进入 Skill 包。",
    filePath: "相对路径",
    fileDescription: "说明",
    fileLanguage: "语言",
    fileContent: "文件内容",
    addFile: "添加文件",
    removeFile: "删除文件",
    assetPathRequired: "文件路径不能为空",
    assetPathUnsafe: "路径必须是安全相对路径，并使用 / 分隔",
    assetPathIncludesDirectory: "路径不要包含 references/ 或 scripts/ 顶层目录",
    assetContentRequired: "文件内容不能为空",
    assetPathDuplicate: "同一目录内文件路径不能重复",
    editMode: "编辑模式",
    previewMode: "预览模式",
    splitMode: "分屏模式",
  },
  feedback: {
    saved: "已保存",
    requestFailed: "请求失败",
    actionFailed: "操作失败",
    rejectionReasonRequired: "驳回原因不能为空",
  },
  version: {
    upgrade: "可升级",
    current: "最新",
    notTracked: "未追踪",
    noPreviousDiff: "没有可对比的历史版本。",
    diff: "版本差异",
    noContentChanges: "内容无变化。",
  },
} as const;
