import type { ActorRole, SkillStatus } from "./domain";

export const PRODUCT_NAME = "Skills Repo";

export const STATUS_LABELS: Record<SkillStatus, string> = {
  draft: "草稿",
  pending_review: "待审核",
  published: "已上架",
  deprecated: "已下架",
  archived: "已归档",
};

export const ROLE_LABELS: Record<ActorRole, string> = {
  employee: "员工",
  admin: "管理员",
};

export const UI_COPY = {
  loading: `正在加载 ${PRODUCT_NAME}...`,
  header: {
    eyebrow: "内部仓库",
    role: "角色",
    resultCount: "当前结果",
    description:
      "Curated internal agent skills for discovery, review, version tracking, and governed reuse across teams.",
    tags: {
      collectedSkills: "Collected SKILL.md files",
      controlledSources: "Controlled Git sources",
      versionAudit: "Version history & audit trail",
    },
  },
  actions: {
    logout: "登出",
    newSkill: "新建 Skill",
    importGit: "导入 Git",
    publish: "上架",
    deprecate: "下架",
    archive: "归档",
    apply: "应用",
    edit: "编辑",
    close: "关闭",
    saveDraftVersion: "保存草稿版本",
    createDraft: "创建草稿",
    upgradeTrackedVersion: "升级当前跟踪版本",
    trackCurrentVersion: "跟踪当前版本",
  },
  stats: {
    totalSkills: "Skills 总数",
    published: "已上架",
    pendingReview: "待审核",
    categories: "分类数",
    recentlyUpdated: "最近更新",
  },
  filters: {
    search: "搜索",
    category: "分类",
    status: "状态",
    teamOrSource: "团队/来源",
    tool: "工具",
    versionState: "版本状态",
    searchPlaceholder: "搜索 Skills、标签、团队...",
    allCategories: "全部分类",
    allStatuses: "全部状态",
    allTeamsOrSources: "全部团队/来源",
    allTools: "全部工具",
    allVersionStates: "全部版本状态",
    upgradeAvailable: "有可升级版本",
    current: "已是最新",
    notTracked: "未跟踪",
    viewMode: "视图模式",
    gridView: "Grid 视图",
    tableView: "Table 视图",
  },
  admin: {
    console: "后台操作",
    selected: "已选",
    category: "分类",
  },
  list: {
    title: "Skills 列表",
    updatedAt: "更新于",
    currentVersion: "当前版本",
    source: "来源",
    versions: "版本",
    maintainers: "维护人",
  },
  detail: {
    eyebrow: "Skill 详情",
    noRelease: "暂无线上版本",
    upgradeTitle: "有可升级版本",
    upgradeText: "你当前跟踪 {trackedVersion}；线上版本是 {currentVersion}。",
    basicInformation: "基础信息",
    category: "分类",
    tools: "适用工具",
    maintainingTeam: "维护团队",
    maintainers: "维护人",
    installMethod: "安装方式",
    dependencies: "依赖说明",
    none: "无",
    readme: "README / 使用说明",
    versionHistory: "版本历史",
    recentAuditTrail: "最近审计记录",
    noMatches: "当前筛选条件下没有匹配的 Skill。",
    published: "发布于",
    draft: "草稿",
    by: "由",
  },
  editor: {
    controlledGit: "受控 Git",
    adminEditor: "后台编辑",
    importTitle: "从受控 Git 导入",
    editTitle: "编辑 Skill",
    createTitle: "新建 Skill",
    repositoryUrl: "仓库 URL",
    repositoryName: "仓库名称",
    skillName: "Skill 名称",
    category: "分类",
    description: "描述",
    compatibleTools: "适用工具",
    maintainingTeam: "维护团队",
    tags: "标签",
    maintainers: "维护人",
    version: "版本号",
    dependencies: "依赖",
    installMethod: "安装方式",
    changelog: "更新说明",
    markdown: "Markdown 内容",
    editMode: "编辑模式",
    previewMode: "预览模式",
    splitMode: "分屏模式",
  },
  feedback: {
    saved: "已保存",
    requestFailed: "请求失败",
    actionFailed: "操作失败",
  },
  version: {
    upgrade: "可升级",
    current: "最新",
    notTracked: "未跟踪",
    noPreviousDiff: "没有可对比的历史版本。",
    diff: "版本差异",
    noContentChanges: "内容无变化。",
  },
} as const;
